version: '2'

services:
  squid:
    image: registry.gitlab.com/strowi/docker-alpine-squid:latest
    build: ./
    restart: always
    ports:
      - 3128:3128

    volumes:
      - /srv/squid:/data
